language: node_js
dist: trusty
node_js:
    - "6"
    - "4"
sudo: false
script:
    npm run test:ci
deploy:
  provider: npm
  email:
    secure: zB13qWQBFkTvUXD4ZF8J9WvCkbu8AFcTsCy1e/yhnIuyTnscn+s5OeRIR0g7po7j7nqjWHdLWYS9HimLdes7TbU5mAw/0nneXORBO6HRag4fNcp0OpwuJ2/yaHMaKqIGqtIQDq5KekEWcKJGtIRrQ0LQ8dzMQ+4QO5TST34nt2bruzR3073OKFjQrZPq1pGQBmlFObdiix4BuWP80Nvfd1cMCwhiACDLQh7xVJxmhEQEv3MDcNrr6NI9cYzNUgZfctnNxpHgcy8bw5kGdGvpBpbhahr258+atJBY67k155IPYXWsEnV+RSckDHT4LNjwCPj9P10bwVwBkGjwVxJHLO3UmsKJptlTJu5rOlRSwgJagK5SB4nzdoxs7x2Fl/h3OjNaVmne52YtN42VQQ+MTsaU9g2WnxplPe4qwjd9dy0tafJHHsar/aIibAF6wbubI2+KxzlIISyreGcsjtuC7eQSGXTikmFaAy4YBXonaUzp/yUfO0N6RLrK4uHkgwx8cVXQ/+SBjww520dRGtjankNO4o0NKVY/S65cD8NpNGZx2eUylziw7eHhZMEWu4wP18OQiHbmrRbzBbLdOWVWJ6qPhzQEkKehOUpddv1bxMiTrIktwHLRAceb1cm5LLjNnNM/m+8KaAkbNCJPvHpvtOr108EqvaQP68i9SLQkQsQ=
  api_key:
    secure: TkIx225yzMNM5QwCmMeH4DLdmlG16vytyPVBaHJkU5RjGgRD3QjbdsR+oysN/50neDg9KyI91Ht1Wa4VJ8on2Yc002HzXQ/gZHpxJOw0oeIUWHubaVQc47V5q4/Et2YQJb4vNR3hlMtV3TLx0IA/dT4NfWKTbTAMWwp4zYUvIqh2dbH0sF0M35c6vwIluvijNE8hjfr9UE5YS1VLSS4+sKDT+kluYztVGeVNtFg9MzVGWmVS6hBmMjmc7yV5lChbSI+TFPj/YjBUr66ehjssBYg8Ay2O90ueI75FxExNEawXg7Y1yJSOtjZ+ECljxMTlsTV7LkH4UzKdCcDrbEV4q0ACWBDXt46QAgBXcKzCzaaMDiR1fd2P6RXEPLUhFjPU0RJgvRzJOW9ufYwQQwjLdxcUTAfWXYXyq+bZAjX3LSfG2rQuwtdOozDlUOSa5pzHHZUlfDmu5RksvA+WVDRIH+CbTO4edod6gluqx3F7bW6niMnvBVr7jlZYf6dTUKgou74i2LGJbCUGPtsGdu9pyEAg3Pmr8EpdZ1GZwjDycOGylqV/VN62z7ie/t2HJpb1RABxX7P1ohlEt7yjWK0X2+m0h6tA1qXuA9E/KDBjIaV29ZFS3OFns0kyxpuKlZGsTAVQUQBnRe4SyDgty4uProQnnJXI3Yvzkjulj76//CI=
  on:
    tags: true
    repo: hlapp/wirelesstags-js
    node: "4"
